### ISSUE TITLE
Using `Promise.reject` triggers deprecation warning

### ISSUE THREAD

**Issue by eridal** [limulus/call-me-maybe#5]
The test is creating a dummy promise, which it then would be entirely disregarded as the test is checking that only the first `resolve` operation actually fulfills.

This is the actual line: https://github.com/limulus/call-me-maybe/blob/master/test/maybeTest.js#L134

And here is the text output:

```text
    ✓ should allow errors thrown in the callback to be uncaught
(node:13030) UnhandledPromiseRejectionWarning: Error: bah
    at call-me-maybe/test/maybeTest.js:134:29
    at call-me-maybe/index.js:11:28
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:13030) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Such text output looks misleading as..

1. it shows the test as correctly passed
2. it shows that there is an underlying issue, as warning

More so, this test will start failing once nodejs changes the warning into an error.

> More info about the deprecation:
>
> https://nodejs.org/api/deprecations.html#deprecations_dep0018_unhandled_promise_rejections
> 

**Solution**:

The test could simple resolve a dummy value, like:

```js
return Promise.resolve("bah")
```

Please let me know if this is worth a PR, I'm more than glad to submit one.

**Comment by limulus** [comment]
Thanks for this, @eridal!

I’m actually having trouble understanding why I have the callback returning a Promise at all. Do you see a reason to keep line 134? It seems like it could just be removed and the test would function as intended?

**Comment by eridal** [comment]
@limulus Oh, you're right!

My understanding was that such return will trigger the _call me again_ that the test is actually trying to make sure wont happen.

So yes, I think that we should get rid of that thing PLUS we need to duplicate the `resolve("foo")` thing, so that the test actually makes sure the promise is being executed twice, like here https://github.com/limulus/call-me-maybe/blob/master/test/maybeTest.js#L124

But what it is still not clear to me is how to make that case fail as promises will make sure to never call the same resolve/reject more than once.. that only happens with callbacks.

**Comment by eridal** [comment]
@limulus any update on this?

**Comment by limulus** [comment]
This has been taken care of in a1e5d9b.
