### ISSUE TITLE
global is undefined 

### ISSUE THREAD

**Issue by sabinadreves** [limulus/call-me-maybe#7]
will this code from pongstr: 

'use strict';

var next = function (f) {
  setTimeout(f, 0);
};

module.exports = function maybe(cb, promise) {
  if (cb) {
    promise.then(
      function (result) {
        next(function () {
          cb(null, result);
        });
      },
      function (err) {
        next(function () {
          cb(err);
        });
      }
    );
    return undefined;
  } else {
    return promise;
  }
}; 

will be merged anytime in this repository ? 
i tried it and then it works, but if i want to use it in a docker container it always loads the current index, which causes me the global undefined error. 

kind regards :)

**Comment by limulus** [comment]
Hi @swana1337. I haven’t seen a PR from @pongstr, but I did take a look at their fork: https://github.com/limulus/call-me-maybe/compare/master...pongstr:master

If you’re running `call-me-maybe` in a Docker container, you must be using some JavaScript runtime. In Node, `global` is always defined. Maybe you’re using another runtime that isn’t defining `global`?

For browsers, I believe bundlers like Webpack will define `global` as an alias to `window`, but if you’re seeing this in a browser or bundler context, it would be good to know what bundler you are using. (Or if you are not using a bundler and using ES Modules.)

**Comment by pongstr** [comment]
hey @swana1337, my fork was for a specific use case and a legacy version of `node-webkit`, if you'd like  to use the fork just install it directly from git e.g., `npm i -s pongstr/call-me-maybe` i dont think  the changes I've made are necessary here.  :)

**Comment by sabinadreves** [comment]
i'm trying to use it with vite but it won't work. 

@pongstr i would like to do that but then i get another error in my pipeline, as i am not allowed to load direclty from a github repo in there :/

**Comment by pongstr** [comment]
the easiest way i can think of to suggest is to directly copy+paste the code block and add it to your project. or create another fork and publish it to npm yourself, either under a different name?

**Comment by limulus** [comment]
Ah, dang, I was afraid it was a non-bundler like Vite or Snowpack. 😅

Unfortunately it may take me a little time to get a new release out. The CI for this project is pretty out of date, and I want to be sure I don’t break any of the packages that depend on this module.

@swana1337, in the meantime, adding a hack to your app may get you past the error. Something like `window.global = window` in the same place you load any pollyfills. The trick is to make sure it runs before `call-me-maybe` is loaded.

**Comment by smeng9** [comment]
Hi @limulus, is there any update to support browser?

The proposed solution
> Something like window.global = window in the same place you load any pollyfills.

does not work as other packages that rely on global to be undefined (to test if in browser or in node and change behavior correspondingly) will break

**Comment by limulus** [comment]
Hi @smeng9! I’ve just released v1.0.2 on the `next` channel which I think should fix this issue. Can you update to this version and see if it fixes it for you? Something along the lines of `npm install call-me-maybe@next` should get it installed.

If it works, I will go ahead and release this version on the `latest` channel.

Thanks!

**Comment by smeng9** [comment]
The `next` branch works for me. Thanks!

**Comment by limulus** [comment]
Thanks @smeng9! v1.0.2 is now live on the `latest` tag in npm.
